[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"